window.FM_DATA = {
  version: 2,
  lessons: [
    {
      id:"radians", code:"3.6.1.1", paper:"Paper 1", title:"Radians, angular displacement and angular speed", sim:"circular",
      lead:"Build the rotational language used throughout circular motion.",
      keywords:["radian","angular displacement","angular speed","frequency","period","tangential speed"],
      formulas:["θ = s/r","ω = Δθ/Δt","ω = 2πf = 2π/T","v = ωr"],
      objectives:["Convert between revolutions, degrees and radians.","Calculate angular speed from frequency or period.","Relate angular motion to tangential speed."],
      retrieval:[["How many radians are in one revolution?","2π rad."],["Define frequency.","Number of complete cycles per second, in hertz."],["State the relation between period and frequency.","T = 1/f."]],
      teach:[
        ["Radian measure","Radian measure links angle directly to arc length. θ = s/r, so one radian is the angle subtended when the arc length equals the radius. A complete revolution is 2π rad and 180° is π rad."],
        ["Angular speed","Angular speed is the rate of change of angular displacement. For uniform rotation, ω = 2πf = 2π/T. Its unit is rad s⁻¹."],
        ["Tangential speed","A point moving in a circle travels arc length s = rθ. Differentiating the relationship gives v = ωr. Points on one rigid object share the same angular speed, but points farther from the axis have a larger tangential speed."],
        ["AQA focus","Use radians in circular-motion equations. Direction of angular velocity is not required by the AQA specification, so focus on magnitude and relationships between θ, ω, v, f and T."]
      ],
      worked:{q:"A turntable rotates at 4.0 rev s⁻¹. A point is 0.18 m from the centre. Find ω and v.",steps:["ω = 2πf = 2π × 4.0 = 25.1 rad s⁻¹","v = ωr = 25.1 × 0.18 = 4.52 m s⁻¹"]},
      activity:"Convert 75°, 210° and 1.5 revolutions to radians, then calculate the tangential speed of a point 0.30 m from the centre of a wheel rotating at 3.2 Hz.",
      mission:{goal:"See why angular speed can be shared while tangential speed changes with radius.",steps:["Set angular speed to 3 rad s⁻¹.","Compare a small and large radius.","Record v and period each time."],record:"Create a two-row table of r, ω, v and T.",conclusion:"Explain which quantities changed and why."},
      check:["At fixed angular speed, doubling radius makes tangential speed…",["half","double","unchanged","four times"],1,"v = ωr."],
      examTip:"Show radian conversions explicitly before substituting into circular-motion equations.",
      misconception:"Radians are dimensionless, but A-level answers normally state rad when quoting an angle.",
      exit:"Why do two points on the same rotating disc have equal ω but different v?"
    },
    {
      id:"centripetal-accel", code:"3.6.1.1", paper:"Paper 1", title:"Centripetal acceleration", sim:"circular",
      lead:"Understand why constant speed around a circle still involves acceleration.",
      keywords:["centripetal","velocity","tangent","radius","acceleration"],
      formulas:["a = v²/r","a = ω²r"],
      objectives:["Explain why circular motion requires acceleration.","Calculate centripetal acceleration.","Relate the velocity and acceleration directions."],
      retrieval:[["Can velocity change if speed is constant?","Yes. Velocity changes when direction changes."],["What is acceleration?","Rate of change of velocity."],["What direction is instantaneous velocity in circular motion?","Tangential to the path."]],
      teach:[
        ["Changing velocity","Uniform circular motion has constant speed but continually changing velocity because the direction changes. A change in velocity means acceleration."],
        ["Direction","Centripetal acceleration is always directed radially inward, toward the centre of the circular path. Instantaneous velocity is tangential, so v and a are perpendicular."],
        ["Magnitude","The magnitude is a = v²/r. Substituting v = ωr gives a = ω²r. At fixed radius, acceleration depends on v²; at fixed angular speed, acceleration is proportional to radius."],
        ["Reasoning","The formula derivation is not examined by AQA, but students should use it confidently and estimate accelerations in real rotating systems."]
      ],
      worked:{q:"A cyclist travels around a 32 m radius bend at 11 m s⁻¹. Find centripetal acceleration.",steps:["a = v²/r","a = 11²/32 = 3.78 m s⁻²"]},
      activity:"Predict the effect on a if speed doubles, radius doubles, or both double. Then verify using the simulation.",
      mission:{goal:"Test the square-law dependence on speed.",steps:["Choose r = 1.0 m.","Record a at two angular speeds that give a 2:1 speed ratio.","Compare the acceleration ratio."],record:"Record v, r and a.",conclusion:"Explain why doubling v produces four times the acceleration."},
      check:["The acceleration of an object in uniform circular motion points…",["along the tangent","toward the centre","away from the centre","in the direction of motion"],1,"Centripetal means centre-seeking."],
      examTip:"If a question asks for direction, write 'toward the centre of the circle', not just 'inward'.",
      misconception:"Constant speed does not mean zero acceleration because velocity includes direction.",
      exit:"Why is uniform circular motion accelerated motion?"
    },
    {
      id:"centripetal-force", code:"3.6.1.1", paper:"Paper 1", title:"Centripetal force and real force systems", sim:"circular",
      lead:"Treat centripetal force as the inward resultant of real forces.",
      keywords:["resultant force","tension","friction","normal contact force","gravity"],
      formulas:["F = mv²/r","F = mω²r"],
      objectives:["Calculate the required inward resultant force.","Identify which real force provides the centripetal force.","Solve circular-motion force problems."],
      retrieval:[["State Newton's second law.","ΣF = ma."],["Name one force that can provide centripetal force.","Examples: tension, friction, gravity, normal contact force."],["What happens if inward resultant force is insufficient?","The object cannot follow the required circular path at that speed/radius."]],
      teach:[
        ["Not an extra force","Centripetal force is not a separate force to add to a free-body diagram. It is the name for the resultant component of the real forces directed toward the centre."],
        ["Equation","Combining F = ma with a = v²/r gives F = mv²/r, or F = mω²r."],
        ["Applications","For a car on a flat bend, friction can provide the inward force. For a satellite, gravity provides it. For a mass on a string, tension may provide all or part of it."],
        ["Exam strategy","Draw the real forces first, choose an inward radial direction, then set the inward resultant equal to mv²/r."]
      ],
      worked:{q:"A 0.65 kg object moves in a horizontal circle of radius 0.80 m at 3.6 m s⁻¹. Find the required inward resultant force.",steps:["F = mv²/r","F = 0.65 × 3.6² / 0.80 = 10.5 N"]},
      activity:"Draw force diagrams for a car on a flat bend, a conical pendulum and a satellite. Identify the force or component that provides the centripetal resultant.",
      mission:{goal:"Connect real force requirements to speed.",steps:["Set mass and radius.","Increase speed gradually.","Watch the required inward force rise."],record:"Record two values of v and F.",conclusion:"Describe the proportionality between F and v."},
      check:["For a satellite in circular orbit, the centripetal force is…",["a separate force","gravity","engine thrust only","air resistance"],1,"Gravity is the inward resultant."],
      examTip:"Write ΣF inward = mv²/r before resolving forces.",
      misconception:"Do not draw a force arrow labelled 'centripetal force' in addition to the forces already acting.",
      exit:"Explain what 'centripetal force' means in one precise sentence."
    },
    {
      id:"shm-condition", code:"3.6.1.2", paper:"Paper 1", title:"The defining condition for SHM", sim:"shm",
      lead:"Recognise simple harmonic motion from its restoring acceleration.",
      keywords:["equilibrium","restoring acceleration","displacement","amplitude","angular frequency"],
      formulas:["a ∝ −x","a = −ω²x"],
      objectives:["State the SHM condition.","Use the defining equation.","Interpret the negative sign physically."],
      retrieval:[["Define equilibrium position.","Position where the resultant force is zero."],["What is amplitude?","Maximum displacement from equilibrium."],["What does a negative sign indicate in a vector equation?","Opposite direction relative to the chosen positive direction."]],
      teach:[
        ["Definition","An oscillator performs SHM when acceleration is directly proportional to displacement from equilibrium and is directed toward equilibrium."],
        ["Equation","The defining equation is a = −ω²x. The negative sign encodes the restoring direction."],
        ["Key positions","At equilibrium x = 0, so a = 0. At maximum displacement x = ±A, acceleration magnitude is maximum."],
        ["What is not constant","Acceleration changes continuously during SHM. It is not a constant-acceleration problem."]
      ],
      worked:{q:"An oscillator has ω = 7.5 rad s⁻¹ and x = +0.040 m. Find a.",steps:["a = −ω²x","a = −7.5² × 0.040 = −2.25 m s⁻²","The negative sign means the acceleration is toward equilibrium."]},
      activity:"For x = +A, +A/2, 0, −A/2 and −A, state the sign and relative magnitude of acceleration.",
      mission:{goal:"Connect displacement to restoring acceleration.",steps:["Pause the oscillator at several positions.","Read x and a.","Compare a/x."],record:"Record x, a and a/x for three non-zero displacements.",conclusion:"Explain why the ratio supports a ∝ −x."},
      check:["At maximum positive displacement, acceleration is…",["zero","maximum positive","maximum negative","constant"],2,"a = −ω²x."],
      examTip:"When defining SHM, include both proportionality and opposite direction.",
      misconception:"SHM does not mean 'any repeating motion'; the restoring-acceleration condition must be satisfied.",
      exit:"State the SHM condition in words and as an equation."
    },
    {
      id:"shm-graphs", code:"3.6.1.2", paper:"Paper 1", title:"SHM displacement, velocity and acceleration graphs", sim:"shm",
      lead:"Use gradients and phase to connect x, v and a.",
      keywords:["phase","gradient","sinusoidal","displacement","velocity","acceleration"],
      formulas:["x = A cos(ωt)","v = −Aω sin(ωt)","a = −Aω² cos(ωt)"],
      objectives:["Sketch x–t, v–t and a–t graphs.","Use gradients to explain graph relationships.","Describe phase differences."],
      retrieval:[["Gradient of x–t graph?","Velocity."],["Gradient of v–t graph?","Acceleration."],["Phase angle for one complete cycle?","2π rad."]],
      teach:[
        ["Displacement graph","If the oscillator starts at +A, a convenient model is x = A cos(ωt)."],
        ["Velocity graph","Velocity is the gradient of the displacement graph. It is zero at the turning points and greatest in magnitude at equilibrium."],
        ["Acceleration graph","Acceleration is the gradient of the velocity graph and also follows a = −ω²x, so acceleration is exactly π rad out of phase with displacement."],
        ["Phase","Velocity is π/2 rad out of phase with displacement. The sign depends on the chosen starting condition and direction, so use the graph physically rather than memorising only a sign."]
      ],
      worked:{q:"An oscillator has A = 0.060 m and f = 1.8 Hz. Find ω and maximum speed.",steps:["ω = 2πf = 11.3 rad s⁻¹","vmax = ωA = 11.3 × 0.060 = 0.679 m s⁻¹"]},
      activity:"Sketch x, v and a over one cycle beginning at x = +A. Mark t = 0, T/4, T/2, 3T/4 and T.",
      mission:{goal:"Observe phase directly.",steps:["Run slowly for one cycle.","Pause at +A, 0, −A and 0.","Compare signs of x, v and a."],record:"Build a four-row phase table.",conclusion:"State the phase difference between x and a."},
      check:["At equilibrium in ideal SHM, speed is…",["zero","maximum","always negative","equal to acceleration"],1,"Kinetic energy and speed are greatest at equilibrium."],
      examTip:"When sketching graphs, align zero crossings and turning points carefully.",
      misconception:"Velocity is not greatest at maximum displacement.",
      exit:"Explain how the v–t graph can be obtained from the x–t graph."
    },
    {
      id:"shm-extremes", code:"3.6.1.2", paper:"Paper 1", title:"Maximum speed, maximum acceleration and speed at displacement", sim:"shm",
      lead:"Calculate how fast an oscillator can move and how acceleration changes with position.",
      keywords:["maximum speed","maximum acceleration","amplitude","angular frequency"],
      formulas:["vmax = ωA","amax = ω²A","v = ±ω√(A² − x²)"],
      objectives:["Calculate vmax and amax.","Calculate speed at a given displacement.","Use signs and directions correctly."],
      retrieval:[["Where is speed maximum?","At equilibrium."],["Where is acceleration magnitude maximum?","At the turning points."],["What is ω in terms of f?","ω = 2πf."]],
      teach:[
        ["Maximum values","From the SHM equations, vmax = ωA and amax = ω²A."],
        ["Speed at a position","At displacement x, v = ±ω√(A² − x²). The ± indicates that the oscillator can pass the same position in either direction."],
        ["Scaling","At fixed amplitude, vmax ∝ ω and amax ∝ ω². At fixed ω, both maxima are proportional to amplitude."],
        ["Units","Use metres, seconds, rad s⁻¹ and m s⁻² consistently."]
      ],
      worked:{q:"A = 0.075 m and f = 2.4 Hz. Find vmax and amax.",steps:["ω = 2πf = 15.1 rad s⁻¹","vmax = 15.1 × 0.075 = 1.13 m s⁻¹","amax = 15.1² × 0.075 = 17.1 m s⁻²"]},
      activity:"For A = 0.10 m and ω = 5.0 rad s⁻¹, calculate speed at x = 0, 0.05 m and 0.10 m.",
      mission:{goal:"Map speed against displacement.",steps:["Set a fixed A and f.","Pause at several x values.","Record speed magnitude."],record:"Make a table of x/A and v/vmax.",conclusion:"Describe where speed is largest and why."},
      check:["If ω doubles with A unchanged, amax becomes…",["double","four times","half","unchanged"],1,"amax = ω²A."],
      examTip:"Use speed magnitude unless the question asks for velocity/direction.",
      misconception:"The same displacement can correspond to two opposite velocities.",
      exit:"Describe x, v and a at an instant when the oscillator passes through equilibrium."
    },
    {
      id:"spring", code:"3.6.1.3", paper:"Paper 1", title:"Mass–spring systems", sim:"spring",
      lead:"Derive the SHM behaviour of an ideal mass–spring oscillator.",
      keywords:["Hooke's law","spring constant","restoring force","period","natural frequency"],
      formulas:["F = −kx","ω = √(k/m)","T = 2π√(m/k)"],
      objectives:["Show why Hooke's law gives SHM.","Calculate period and natural frequency.","Predict effects of m and k."],
      retrieval:[["State Hooke's law.","F = kΔL within the limit of proportionality."],["Unit of k?","N m⁻¹."],["What condition defines SHM?","a ∝ −x."]],
      teach:[
        ["Restoring force","Measured from equilibrium, an ideal spring gives F = −kx. The sign shows that force is opposite displacement."],
        ["Link to SHM","Using F = ma gives a = −(k/m)x. Comparing with a = −ω²x gives ω² = k/m."],
        ["Period","Therefore T = 2π√(m/k). Increasing mass increases period; increasing stiffness decreases period."],
        ["Vertical systems","A vertical spring has a shifted equilibrium because of weight, but small oscillations about equilibrium have the same ideal period relation."]
      ],
      worked:{q:"A 0.35 kg mass oscillates on a spring of k = 18 N m⁻¹. Find T.",steps:["T = 2π√(m/k)","T = 2π√(0.35/18) = 0.876 s"]},
      activity:"Rearrange T² = 4π²m/k and predict the graph expected for T² against m.",
      mission:{goal:"Verify the mass dependence experimentally.",steps:["Keep k fixed.","Take simulated readings at several masses.","Plot or inspect T² against m."],record:"Record m, T and T².",conclusion:"Explain why a straight line is expected and what its gradient represents."},
      check:["Doubling k changes T by a factor of…",["2","√2","1/√2","1/2"],2,"T ∝ 1/√k."],
      examTip:"If deriving the spring period, compare coefficients in a = −(k/m)x and a = −ω²x.",
      misconception:"The static extension of a vertical spring is not the oscillation amplitude unless stated.",
      exit:"Show in two lines how Hooke's law produces the SHM condition."
    },
    {
      id:"pendulum", code:"3.6.1.3", paper:"Paper 1", title:"Simple pendulum and small-angle SHM", sim:"pendulum",
      lead:"Understand why a simple pendulum is only approximately SHM.",
      keywords:["small-angle approximation","radian","pendulum length","period","restoring force"],
      formulas:["T = 2π√(L/g)","ω = √(g/L)","sinθ ≈ θ for small θ in rad"],
      objectives:["Use the simple-pendulum period equation.","Explain the small-angle approximation.","Predict how L and g affect T."],
      retrieval:[["Tangential component of weight?","mg sinθ."],["What does sinθ ≈ θ require?","A small angle measured in radians."],["Does ideal pendulum period depend on bob mass?","No."]],
      teach:[
        ["Restoring effect","The tangential component of weight acts toward equilibrium. Its exact dependence is sinθ, so the motion is not exactly SHM at large angles."],
        ["Small-angle approximation","For small θ in radians, sinθ ≈ θ. Arc displacement x ≈ Lθ, making restoring acceleration approximately proportional to −x."],
        ["Period","The small-angle result is T = 2π√(L/g). Mass does not appear."],
        ["Practical detail","Measure length from the pivot to the centre of the bob, use a small release angle, time many oscillations and repeat."]
      ],
      worked:{q:"Find T for a 0.90 m pendulum at g = 9.81 m s⁻².",steps:["T = 2π√(L/g)","T = 2π√(0.90/9.81) = 1.90 s"]},
      activity:"Predict the effect of quadrupling L. Then explain why increasing bob mass should not change the ideal period.",
      mission:{goal:"Explore where the small-angle model works best.",steps:["Choose a fixed length.","Compare a small and larger release angle.","Observe the simulated period."],record:"Record angle and period for two cases.",conclusion:"Explain why the textbook equation is described as a small-angle approximation."},
      check:["Which change increases the ideal period?",["Increase bob mass","Increase length","Increase bob density","Decrease amplitude from 8° to 4°"],1,"T ∝ √L."],
      examTip:"State that θ must be in radians when using sinθ ≈ θ.",
      misconception:"A pendulum is not exactly SHM for arbitrary amplitudes.",
      exit:"Why is the pendulum period equation an approximation?"
    },
    {
      id:"shm-energy", code:"3.6.1.3", paper:"Paper 1", title:"Energy in SHM", sim:"shmEnergy",
      lead:"Track kinetic, potential and total energy with displacement and time.",
      keywords:["kinetic energy","potential energy","total energy","turning point","equilibrium"],
      formulas:["Etotal = ½kA²","Ep = ½kx²","Ek = ½k(A² − x²)"],
      objectives:["Describe energy transfers in SHM.","Calculate energy at a given displacement.","Interpret energy–displacement and energy–time graphs."],
      retrieval:[["Where is speed maximum?","At equilibrium."],["Where is spring PE maximum?","At maximum displacement."],["In ideal SHM, what happens to total mechanical energy?","It remains constant."]],
      teach:[
        ["Conservation","With no damping, total mechanical energy remains constant while energy transfers between kinetic and potential stores."],
        ["Turning points","At x = ±A, speed and kinetic energy are zero; potential energy is maximum."],
        ["Equilibrium","At x = 0, potential energy is minimum and kinetic energy is maximum."],
        ["Graph shape","For a spring, Ep = ½kx², so potential-energy variation with displacement is parabolic. Total energy is constant at ½kA²."]
      ],
      worked:{q:"k = 30 N m⁻¹, A = 0.12 m. Find total energy and KE at x = 0.080 m.",steps:["Etotal = ½kA² = 0.216 J","Ep = ½kx² = 0.096 J","Ek = 0.216 − 0.096 = 0.120 J"]},
      activity:"Sketch KE, PE and total energy against displacement from −A to +A.",
      mission:{goal:"Connect motion to energy transfer.",steps:["Run one full cycle.","Pause at a turning point and equilibrium.","Compare KE, PE and total energy."],record:"Record x, v, KE and PE at three positions.",conclusion:"Explain why total energy stays constant in the ideal model."},
      check:["At x = 0 in an ideal spring oscillator…",["PE is maximum","KE is maximum","total energy is zero","acceleration is maximum"],1,"The object moves fastest at equilibrium."],
      examTip:"Energy depends on squared displacement, so do not copy the shape of the x–t graph onto an energy graph.",
      misconception:"KE and PE do not each remain constant; only their sum does in undamped SHM.",
      exit:"Explain the energy transfers over one quarter-cycle from x = +A to x = 0."
    },
    {
      id:"damping", code:"3.6.1.3", paper:"Paper 1", title:"Damping and return to equilibrium", sim:"damping",
      lead:"Understand how resistive forces change amplitude and energy.",
      keywords:["damping","light damping","critical damping","heavy damping","energy dissipation"],
      formulas:["mechanical energy decreases when work is done against resistive forces"],
      objectives:["Describe light, critical and heavy damping.","Explain amplitude decay using energy.","Recognise damped motion graphs."],
      retrieval:[["What is a resistive force?","A force opposing motion."],["What happens to mechanical energy if resistive forces do work?","It decreases, with energy transferred to the surroundings."],["Define amplitude.","Maximum displacement from equilibrium."]],
      teach:[
        ["Light damping","The system continues to oscillate, but amplitude decreases progressively as energy is dissipated."],
        ["Critical damping","The system returns to equilibrium in the shortest time without oscillating."],
        ["Heavy damping","The system also returns without oscillating but more slowly than under critical damping."],
        ["Applications","Damping is engineered in suspension systems, door closers and measuring instruments to control unwanted oscillations."]
      ],
      worked:{q:"Why does maximum speed decrease in a lightly damped oscillator?",steps:["Resistive forces do negative work.","Mechanical energy decreases.","Lower total energy means smaller amplitude and lower maximum speed."]},
      activity:"Sketch displacement–time curves for light damping, critical damping and heavy damping.",
      mission:{goal:"Compare damping regimes.",steps:["Start with low damping.","Increase damping through the critical region.","Observe whether the system overshoots equilibrium."],record:"Classify three damping settings by behaviour.",conclusion:"Identify the fastest non-oscillatory response."},
      check:["Critical damping is useful because it…",["maximises resonance","returns to equilibrium quickly without oscillation","removes the restoring force","increases natural frequency indefinitely"],1,"That is the defining useful behaviour."],
      examTip:"Describe damping in terms of energy transfer, not simply 'the oscillations get smaller'.",
      misconception:"Critical damping is not the same as maximum damping.",
      exit:"Compare critical and heavy damping."
    },
    {
      id:"resonance", code:"3.6.1.4", paper:"Paper 1", title:"Free vibrations, forced vibrations and resonance", sim:"resonance",
      lead:"Link driving frequency, natural frequency, damping and response amplitude.",
      keywords:["natural frequency","driving frequency","forced vibration","resonance","sharpness"],
      formulas:["resonance occurs when fdrive is close to fnatural"],
      objectives:["Distinguish free and forced vibrations.","Explain resonance.","Describe how damping changes a resonance curve."],
      retrieval:[["Define natural frequency.","Frequency at which a displaced system tends to oscillate freely."],["Define a forced vibration.","Oscillation maintained by a periodic driving force."],["What does damping do to energy?","Transfers mechanical energy to the surroundings."]],
      teach:[
        ["Free vibration","A system displaced and released oscillates at its natural frequency, subject to damping."],
        ["Forced vibration","A periodic external force drives the system. In steady conditions the response follows the driving frequency."],
        ["Resonance","When driving frequency is close to natural frequency, energy transfer is especially effective and response amplitude becomes large."],
        ["Damping and sharpness","Greater damping reduces the peak response and broadens the resonance curve. Mechanical examples include suspension systems, bridges and driven oscillators. Stationary-wave examples include strings and air columns, where resonance occurs when the driving frequency matches an allowed natural mode."]
      ],
      worked:{q:"A system's natural frequency is 3.2 Hz. Where should the largest response occur when damping is small?",steps:["Resonance occurs when driving frequency ≈ natural frequency.","Largest response is therefore near 3.2 Hz."]},
      activity:"Give one situation where resonance is useful and one where it could be undesirable. Explain the role of damping.",
      mission:{goal:"Build and interpret a resonance curve.",steps:["Keep natural frequency fixed.","Sweep driving frequency across it.","Repeat with larger damping."],record:"Record peak frequency, peak amplitude and approximate width.",conclusion:"Explain how damping changes sharpness."},
      check:["Increasing damping makes the resonance peak generally…",["higher and narrower","lower and broader","unchanged","move to zero frequency"],1,"Greater damping reduces and broadens the peak."],
      examTip:"Use 'driving frequency close to natural frequency' and 'efficient energy transfer' in resonance explanations.",
      misconception:"Resonance is not defined simply by 'large amplitude'.",
      exit:"Explain why damping can protect a mechanical system near resonance."
    },

    {
      id:"internal-energy", code:"3.6.2.1", paper:"Paper 2", title:"Internal energy and the first-law idea", sim:"thermalParticles",
      lead:"Build a particle-level model of internal energy and energy transfer.",
      keywords:["internal energy","random kinetic energy","potential energy","heating","work"],
      formulas:["ΔU = energy transferred by heating + work done on the system (qualitative sign idea)"],
      objectives:["Define internal energy.","Distinguish heating from temperature.","Explain qualitatively how heating and work alter internal energy."],
      retrieval:[["What energy do moving particles possess?","Kinetic energy."],["What can intermolecular separation affect?","Potential energy."],["Is temperature itself energy?","No. Temperature is related to the thermal state/mean random kinetic energy in suitable models."]],
      teach:[
        ["Definition","Internal energy is the sum of the randomly distributed kinetic energies and potential energies of the particles in a body."],
        ["Two routes to change internal energy","Internal energy increases when energy is transferred to a system by heating or when work is done on the system. It decreases when energy leaves by heating or the system does work on its surroundings."],
        ["Temperature link","Raising temperature generally increases the random kinetic-energy part of internal energy. The exact partition depends on the material and state."],
        ["State changes","During a change of state at constant temperature, average kinetic energy does not increase; the energy supplied changes the particle potential-energy contribution instead."]
      ],
      worked:{q:"Why can internal energy increase while temperature stays constant during melting?",steps:["Temperature staying constant means mean random kinetic energy does not increase.","Energy supplied changes particle arrangement/separation.","The potential-energy contribution to internal energy increases."]},
      activity:"Compare heating a gas in a rigid container with compressing it rapidly. Describe the energy-transfer route in each case.",
      mission:{goal:"Separate kinetic and potential contributions.",steps:["Increase temperature without changing state.","Then trigger a state-change region.","Watch which energy representation changes."],record:"Note particle speed and separation/arrangement in each case.",conclusion:"Explain why internal energy can change without a temperature rise."},
      check:["Internal energy is the total of particles' randomly distributed…",["kinetic energy only","potential energy only","kinetic and potential energies","chemical energy only"],2,"Both contributions are included."],
      examTip:"Do not define internal energy as 'heat stored in an object'.",
      misconception:"Heating is an energy-transfer process; it is not a substance contained in an object.",
      exit:"State two different ways of increasing a system's internal energy."
    },
    {
      id:"specific-heat", code:"3.6.2.1", paper:"Paper 2", title:"Specific heat capacity and electrical heating", sim:"calorimetry",
      lead:"Calculate temperature change and analyse an electrical heating experiment.",
      keywords:["specific heat capacity","thermal capacity","electrical power","energy transfer","uncertainty"],
      formulas:["Q = mcΔT","E = Pt = VIt"],
      objectives:["Use Q = mcΔT.","Plan an electrical specific-heat experiment.","Identify random and systematic errors and improvements."],
      retrieval:[["Unit of specific heat capacity?","J kg⁻¹ K⁻¹."],["Electrical power in a heater?","P = VI."],["Why can ΔT in K equal ΔT in °C?","Kelvin and Celsius intervals have the same size."]],
      teach:[
        ["Meaning of c","Specific heat capacity is the energy required to raise the temperature of 1 kg of a substance by 1 K, without a change of state."],
        ["Calculation","Q = mcΔT. A large c means more energy is required for the same mass and temperature rise."],
        ["Electrical method","Measure mass, heater voltage/current (or power), time and temperature change. Ideally Eelectrical = mcΔT."],
        ["Evaluation","Heat loss to surroundings and energy absorbed by the container/heater cause systematic underestimation/overestimation if ignored. Insulation, a lid, temperature logging, mixing and accounting for apparatus heat capacity can improve the method."]
      ],
      worked:{q:"A 0.80 kg block receives 18 kJ and warms by 24 K. Find c.",steps:["c = Q/(mΔT)","c = 18000/(0.80×24) = 938 J kg⁻¹ K⁻¹"]},
      activity:"Design a method to measure c using a heater, ammeter, voltmeter, thermometer/data logger, balance and insulation. Include one random and one systematic error.",
      mission:{goal:"See how mass, power and c control the heating rate.",steps:["Hold two variables fixed.","Change one of mass, power or c.","Compare the temperature–time slope."],record:"Record initial slope for two settings.",conclusion:"Relate the slope to P/(mc)."},
      check:["For fixed power and mass, a larger specific heat capacity gives…",["faster temperature rise","slower temperature rise","no change","instant boiling"],1,"More energy is needed per kelvin."],
      examTip:"For electrical heating, write E = Pt and Q = mcΔT before equating them.",
      misconception:"Specific heat capacity is not the same as total heat capacity; c is per kilogram.",
      exit:"Why does heat loss tend to make a simple electrical measurement of c inaccurate?"
    },
    {
      id:"continuous-flow", code:"3.6.2.1", paper:"Paper 2", title:"Continuous-flow heating calculations", sim:"flowHeating",
      lead:"Apply energy balance to matter moving continuously through a heater.",
      keywords:["mass flow rate","power","steady state","temperature rise","energy balance"],
      formulas:["P = ṁcΔT","ṁ = Δm/Δt"],
      objectives:["Use mass flow rate in thermal calculations.","Link heater power to steady temperature rise.","Interpret continuous-flow measurements."],
      retrieval:[["What is power?","Rate of energy transfer."],["What is mass flow rate?","Mass passing a point per unit time."],["What does steady state imply here?","Temperatures and flow conditions are stable with time."]],
      teach:[
        ["From batch to flow","For a mass m heated through ΔT, Q = mcΔT. Dividing by time gives power P = (m/t)cΔT."],
        ["Mass flow rate","Define ṁ = m/t, so P = ṁcΔT when losses are negligible."],
        ["Practical interpretation","At fixed power, increasing flow rate reduces temperature rise because the supplied energy is shared among more mass each second."],
        ["Losses","Real systems lose energy to surroundings. Comparing measurements at different powers/flow rates can help estimate or reduce the effect of heat loss."]
      ],
      worked:{q:"Water flows at 0.020 kg s⁻¹ through a 1.5 kW heater. Take c = 4200 J kg⁻¹ K⁻¹. Estimate ΔT.",steps:["P = ṁcΔT","ΔT = 1500/(0.020×4200) = 17.9 K"]},
      activity:"Calculate ΔT for flow rates 0.010, 0.020 and 0.030 kg s⁻¹ at the same power.",
      mission:{goal:"Visualise the inverse relation between flow rate and temperature rise.",steps:["Fix heater power.","Double mass flow rate.","Compare outlet temperature rise."],record:"Record ṁ and ΔT.",conclusion:"Explain the inverse relationship from energy per second."},
      check:["At fixed heater power, doubling mass flow rate ideally makes ΔT…",["double","half","unchanged","four times"],1,"P = ṁcΔT."],
      examTip:"Convert g s⁻¹ to kg s⁻¹ before substitution.",
      misconception:"Do not use the total mass that has passed through; use mass per unit time in a steady-flow equation.",
      exit:"Derive P = ṁcΔT from Q = mcΔT."
    },
    {
      id:"latent-heat", code:"3.6.2.1", paper:"Paper 2", title:"Changes of state, latent heat and heating curves", sim:"heatingCurve",
      lead:"Explain why energy can be supplied with no temperature change.",
      keywords:["specific latent heat","melting","boiling","potential energy","heating curve"],
      formulas:["Q = ml"],
      objectives:["Use Q = ml.","Explain constant-temperature phase changes.","Interpret heating curves."],
      retrieval:[["What does temperature track in a particle model?","The average random kinetic-energy scale of particles."],["What is a phase change?","A change of state such as melting or boiling."],["Unit of specific latent heat?","J kg⁻¹."]],
      teach:[
        ["Definition","Specific latent heat l is the energy required per kilogram to change state without a temperature change."],
        ["Particle explanation","During a phase change, supplied energy changes the particle potential-energy arrangement rather than increasing average kinetic energy, so temperature remains constant for a pure substance at constant pressure."],
        ["Heating curve","Sloping regions show temperature rise within one phase. Flat regions show a change of state while energy continues to be supplied. AQA also highlights using a data logger and temperature sensor to record temperature against time while energy is supplied at a constant rate."],
        ["Calculation","Q = ml. Different phase changes have different latent heats, e.g. fusion and vaporisation."]
      ],
      worked:{q:"How much energy is required to melt 0.25 kg of a material with lf = 2.1×10⁵ J kg⁻¹?",steps:["Q = ml","Q = 0.25 × 2.1×10⁵ = 5.25×10⁴ J"]},
      activity:"Sketch a heating curve from solid to gas and annotate where kinetic and potential-energy contributions change. Then describe how a temperature sensor and data logger could collect the same curve when heating at constant power.",
      mission:{goal:"Link plateaus to particle energy changes.",steps:["Run the heating curve.","Pause on a sloped region and a plateau.","Compare particle speed and arrangement."],record:"Note temperature behaviour and energy destination.",conclusion:"Explain why a plateau does not mean 'no energy is being transferred'."},
      check:["During melting at constant temperature, supplied energy mainly increases…",["mean kinetic energy","particle potential-energy contribution","mass","specific heat capacity"],1,"The state changes while temperature stays constant."],
      examTip:"If a multi-stage problem includes heating and a phase change, calculate each energy contribution separately and add them.",
      misconception:"Temperature staying constant does not mean internal energy stays constant.",
      exit:"Explain a flat section of a heating curve using particle energy."
    },
    {
      id:"gas-laws", code:"3.6.2.2", paper:"Paper 2", title:"Experimental gas laws", sim:"gasLaws",
      lead:"Connect pressure, volume and temperature through experimental relationships.",
      keywords:["Boyle's law","Charles's law","pressure law","constant temperature","constant pressure"],
      formulas:["pV = constant at constant T","V/T = constant at constant p","p/T = constant at constant V"],
      objectives:["State the conditions for each gas law.","Use Kelvin temperature.","Interpret linearised gas-law graphs."],
      retrieval:[["What must temperature be measured in for gas laws?","Kelvin."],["State Boyle's law condition.","Constant temperature and fixed amount of gas."],["What does inverse proportionality mean?","One variable increases as the other decreases so their product is constant."]],
      teach:[
        ["Boyle's law","For a fixed mass of gas at constant temperature, p ∝ 1/V, so pV is constant."],
        ["Charles's law","At constant pressure, V ∝ T on the kelvin scale."],
        ["Pressure law","At constant volume, p ∝ T on the kelvin scale."],
        ["Graphs","Useful linear plots include p against 1/V, V against T(K), and p against T(K). Conditions must be controlled because changing more than one independent variable breaks the simple relationship."]
      ],
      worked:{q:"A gas occupies 2.4×10⁻³ m³ at 1.1×10⁵ Pa. At constant temperature it is compressed to 1.5×10⁻³ m³. Find final pressure.",steps:["p₁V₁ = p₂V₂","p₂ = 1.1×10⁵ × 2.4/1.5 = 1.76×10⁵ Pa"]},
      activity:"For Boyle's law, explain why measurements should be taken slowly and why temperature must be allowed to stabilise.",
      mission:{goal:"Build all three gas-law relationships.",steps:["Lock T and change V.","Lock p and change T.","Lock V and change T."],record:"Record pairs of variables for each mode.",conclusion:"State the proportionality and controlled variable each time."},
      check:["For a fixed gas at constant temperature, halving volume ideally makes pressure…",["half","double","unchanged","four times"],1,"pV = constant."],
      examTip:"Always convert Celsius to kelvin before using temperature ratios.",
      misconception:"Boyle's law is not valid if the gas temperature changes significantly during compression.",
      exit:"State Boyle's and Charles's laws including their required conditions."
    },
    {
      id:"absolute-zero", code:"3.6.2.2", paper:"Paper 2", title:"Absolute zero and the kelvin scale", sim:"gasLaws",
      lead:"Understand why absolute temperature is fundamental to gas behaviour.",
      keywords:["absolute zero","kelvin","Celsius","extrapolation","thermodynamic temperature"],
      formulas:["T/K = θ/°C + 273.15"],
      objectives:["Convert between Celsius and kelvin.","Explain the concept of absolute zero.","Interpret extrapolation of gas-law graphs."],
      retrieval:[["What is 0 °C in kelvin?","273.15 K."],["Can kelvin temperature be negative in ordinary thermodynamics?","No; 0 K is the lower bound of the thermodynamic scale."],["Why is Celsius unsuitable in p/T proportionality?","Its zero is not absolute zero."]],
      teach:[
        ["Kelvin scale","The kelvin scale begins at absolute zero. Temperature intervals of 1 K and 1 °C are equal in size, but their zero points differ."],
        ["Conversion","T(K) = θ(°C) + 273.15. In A-level calculations 273 is often adequate unless precision demands otherwise."],
        ["Gas evidence","For an idealised gas, extrapolating V–temperature or p–temperature data toward zero volume/pressure suggests an intercept near −273 °C, motivating the concept of absolute zero."],
        ["Meaning","At 0 K the classical ideal-gas model corresponds to the minimum thermal-motion limit; do not describe real matter with the naive statement that 'all particles stop'."]
      ],
      worked:{q:"Convert −40 °C and 127 °C to kelvin.",steps:["−40 + 273.15 = 233.15 K","127 + 273.15 = 400.15 K"]},
      activity:"A gas has volume 75 cm³ at 300 K. Estimate its volume at 360 K at constant pressure.",
      mission:{goal:"See why proportional gas laws require kelvin.",steps:["Plot/observe V against T in kelvin.","Switch display to Celsius.","Compare the intercept."],record:"Note whether the graph passes through the origin in each scale.",conclusion:"Explain why kelvin gives direct proportionality."},
      check:["20 °C is approximately…",["20 K","253 K","293 K","313 K"],2,"20 + 273 ≈ 293 K."],
      examTip:"Write the conversion to kelvin explicitly; it prevents one of the most common gas-law errors.",
      misconception:"0 °C is not absolute zero.",
      exit:"Why must absolute temperature be used in ideal-gas equations?"
    },
    {
      id:"ideal-gas-moles", code:"3.6.2.2", paper:"Paper 2", title:"Ideal gas equation using moles", sim:"idealGas",
      lead:"Use pV = nRT and connect macroscopic variables to amount of gas.",
      keywords:["ideal gas","mole","molar gas constant","molar mass","amount of substance"],
      formulas:["pV = nRT","n = m/M","R = 8.31 J mol⁻¹ K⁻¹"],
      objectives:["Use pV = nRT.","Calculate amount of substance from mass and molar mass.","Use consistent SI units."],
      retrieval:[["SI unit of pressure?","Pa."],["SI unit of volume?","m³."],["What is one mole?","An amount containing Avogadro's number of specified entities."]],
      teach:[
        ["Equation","For an ideal gas, pV = nRT. Here p is pressure in Pa, V in m³, n in mol, T in K and R is the molar gas constant."],
        ["Amount of gas","n = m/M, where M is molar mass in kg mol⁻¹ if mass is in kg."],
        ["Idealisation","The ideal-gas equation is a model that becomes a good approximation for many real gases at sufficiently low density and away from condensation."],
        ["Problem solving","Convert cm³ or dm³ to m³ and Celsius to kelvin before substitution."]
      ],
      worked:{q:"0.20 mol of ideal gas is at 300 K in 4.0×10⁻³ m³. Find pressure.",steps:["p = nRT/V","p = 0.20×8.31×300/(4.0×10⁻³) = 1.25×10⁵ Pa"]},
      activity:"Find the amount in moles of 8.8 g of CO₂ using M = 44 g mol⁻¹, then use it in an ideal-gas calculation.",
      mission:{goal:"Relate p, V, T and n in one model.",steps:["Hold n fixed and vary T.","Then hold T fixed and vary V.","Observe pressure."],record:"Record two states and verify pV/(nT) is approximately constant.",conclusion:"Identify the constant represented by the ratio."},
      check:["In pV = nRT, temperature must be in…",["°C","K","either scale without conversion","J"],1,"Absolute temperature is required."],
      examTip:"Write units alongside each converted quantity before substitution.",
      misconception:"Do not use molar mass in g mol⁻¹ if the rest of the calculation is in SI units without handling the conversion.",
      exit:"What assumptions are implied when a real gas is treated as ideal?"
    },
    {
      id:"ideal-gas-molecules", code:"3.6.2.2", paper:"Paper 2", title:"Ideal gas equation using molecules and constants", sim:"idealGas",
      lead:"Move between mole-scale and molecule-scale descriptions.",
      keywords:["Avogadro constant","Boltzmann constant","molecular mass","number of molecules"],
      formulas:["pV = NkT","N = nNA","k = R/NA","NA ≈ 6.02×10²³ mol⁻¹","k ≈ 1.38×10⁻²³ J K⁻¹"],
      objectives:["Use pV = NkT.","Convert between moles and molecule number.","Relate R, k and NA."],
      retrieval:[["Symbol for Avogadro constant?","N_A."],["What does N represent in pV = NkT?","Number of molecules/particles in the gas sample."],["Relation between R and k?","R = N_A k."]],
      teach:[
        ["Molecular form","The ideal-gas equation can be written pV = NkT, where N is the number of molecules and k is the Boltzmann constant."],
        ["Link to moles","N = nN_A. Substituting this into pV = NkT gives pV = nN_AkT, so R = N_Ak."],
        ["Mass scales","Molar mass is mass per mole. Molecular mass in kilograms is approximately molar mass divided by N_A."],
        ["Choice of equation","Use pV = nRT when amount is in moles, and pV = NkT when the number of particles is given or required."]
      ],
      worked:{q:"An ideal gas has N = 3.0×10²² molecules at 290 K in 8.0×10⁻⁴ m³. Find p.",steps:["p = NkT/V","p = 3.0×10²² × 1.38×10⁻²³ × 290 /(8.0×10⁻⁴) ≈ 1.50×10⁵ Pa"]},
      activity:"Show numerically that R ≈ N_Ak using standard values.",
      mission:{goal:"Connect microscopic and macroscopic counts.",steps:["Set an amount in moles.","View the corresponding particle number.","Compare pV/(nT) and pV/(NT)."],record:"Record both ratios.",conclusion:"Explain why their constants differ by N_A."},
      check:["Boltzmann constant links temperature to an energy scale per…",["mole","particle","kilogram","cubic metre"],1,"k is the per-particle constant."],
      examTip:"Check whether the question gives n or N before choosing R or k.",
      misconception:"n and N are not interchangeable: n is moles, N is number of particles.",
      exit:"Derive R = N_Ak from the two ideal-gas equations."
    },
    {
      id:"rp8-boyle", code:"3.6.2.2 / RP8", paper:"Paper 3 skills + Paper 2 content", title:"Required Practical 8A: Boyle's law", sim:"boylePractical",
      lead:"Investigate pressure–volume behaviour at constant temperature.",
      keywords:["Boyle's law","constant temperature","pressure sensor","volume","linearisation","uncertainty"],
      formulas:["pV = constant","p ∝ 1/V"],
      objectives:["Describe an RP8 Boyle's law method.","Process data using p against 1/V or pV.","Evaluate control of temperature and measurement uncertainty."],
      retrieval:[["State Boyle's law.","For a fixed gas at constant T, pV is constant."],["What graph should be straight?","p against 1/V."],["Why change volume slowly?","To reduce temperature changes and allow thermal equilibrium."]],
      teach:[
        ["Method","Trap a fixed amount of gas, vary volume and measure pressure. Keep temperature as constant as possible."],
        ["Data processing","A p–V curve is inverse. A graph of p against 1/V should be linear through the origin ideally, or calculate pV for each reading."],
        ["Control","Compression can warm a gas and expansion can cool it, so adjust slowly and allow time for thermal equilibrium."],
        ["Evaluation","Consider pressure-sensor zero/calibration, volume scale resolution, dead volume, leaks and parallax where applicable."]
      ],
      worked:{q:"Measured p = 1.60×10⁵ Pa at V = 50 cm³. Calculate pV in SI units.",steps:["50 cm³ = 50×10⁻⁶ m³","pV = 1.60×10⁵ × 50×10⁻⁶ = 8.0 J"]},
      activity:"Explain how you would decide from a graph whether the data support Boyle's law.",
      mission:{goal:"Collect a realistic Boyle's law data set.",steps:["Change volume in at least five steps.","Take pressure readings after settling.","Inspect p against 1/V."],record:"Save V, p, 1/V and pV.",conclusion:"Use the graph and pV consistency to judge the law."},
      check:["The best simple linearised plot for Boyle's law is…",["p against V","p against 1/V","V against T","p against T"],1,"p ∝ 1/V."],
      examTip:"State how temperature is controlled; it is central to the validity of the relationship.",
      misconception:"A smooth inverse curve alone is weaker evidence than a correctly linearised plot with uncertainties.",
      exit:"Name two experimental effects that could make pV vary across the data set."
    },
    {
      id:"rp8-charles", code:"3.6.2.2 / RP8", paper:"Paper 3 skills + Paper 2 content", title:"Required Practical 8B: Charles's law", sim:"charlesPractical",
      lead:"Investigate volume–temperature behaviour at constant pressure.",
      keywords:["Charles's law","kelvin","constant pressure","water bath","absolute zero"],
      formulas:["V/T = constant","V ∝ T"],
      objectives:["Describe an RP8 Charles's law method.","Use kelvin temperature.","Interpret V–T data and extrapolation."],
      retrieval:[["State Charles's law.","For a fixed gas at constant pressure, V ∝ absolute temperature."],["Why use a water bath?","To control and equilibrate gas temperature."],["Why convert °C to K?","Direct proportionality is with absolute temperature."]],
      teach:[
        ["Method","A trapped gas at approximately constant pressure is placed in water baths at different temperatures. Allow time to reach thermal equilibrium before measuring volume."],
        ["Graph","Plot V against T in kelvin. Ideal behaviour is linear and extrapolates toward zero volume at 0 K."],
        ["Controls","Keep pressure constant and the amount of gas fixed. Avoid leaks and read volume consistently."],
        ["Evaluation","Thermometer calibration, thermal lag, volume resolution and failure to equilibrate are important sources of uncertainty/systematic error."]
      ],
      worked:{q:"A gas has V = 68 cm³ at 290 K. Estimate V at 330 K at constant pressure.",steps:["V₁/T₁ = V₂/T₂","V₂ = 68×330/290 = 77.4 cm³"]},
      activity:"Explain why plotting V against Celsius temperature does not pass through the origin even if Charles's law is obeyed.",
      mission:{goal:"Generate a Charles's law graph.",steps:["Choose several bath temperatures.","Allow the model to equilibrate.","Record volume."],record:"Record θ/°C, T/K and V.",conclusion:"Explain the significance of the kelvin-scale intercept."},
      check:["At constant pressure, increasing absolute temperature by 10% ideally makes volume…",["decrease 10%","increase 10%","double","unchanged"],1,"V ∝ T."],
      examTip:"Use kelvin in calculations even if the apparatus reads °C.",
      misconception:"The extrapolated zero-volume point is a model-based indication of absolute zero, not a claim that a real gas remains ideal all the way to 0 K.",
      exit:"Why should the gas be allowed to reach thermal equilibrium before each reading?"
    },
    {
      id:"brownian-model", code:"3.6.2.3", paper:"Paper 2", title:"Brownian motion and the molecular model of gases", sim:"brownian",
      lead:"Use microscopic motion to explain macroscopic gas behaviour.",
      keywords:["Brownian motion","random motion","collisions","pressure","empirical law","theoretical model"],
      formulas:["pressure arises from momentum transfer in molecular collisions"],
      objectives:["Explain Brownian motion as evidence for atoms/molecules.","Explain pressure using collisions.","Distinguish empirical gas laws from a theoretical molecular model."],
      retrieval:[["What causes gas pressure on a wall?","Momentum changes when molecules collide with the wall."],["What does random mean in this context?","Directions and collision events vary unpredictably microscopically."],["What is an empirical law?","A relationship established from observations/measurements."]],
      teach:[
        ["Brownian motion","Small visible particles suspended in a fluid show irregular motion because of unequal, rapidly changing collisions from much smaller invisible molecules. This provided evidence for atomic/molecular reality."],
        ["Pressure","Gas molecules collide with container walls and change momentum. The walls exert forces on the molecules, so by Newton's third law the molecules exert forces on the walls. Many collisions produce macroscopic pressure."],
        ["p, V and T","Smaller volume increases collision rate per area; higher temperature increases molecular speeds and momentum changes. These ideas explain the observed gas-law trends."],
        ["Evidence and models","The gas laws are empirical relationships from experiment. Kinetic theory is a theoretical model designed to explain them and make further predictions."]
      ],
      worked:{q:"Why does pressure rise when an ideal gas is heated at fixed volume?",steps:["Higher T means greater mean molecular kinetic energy.","Molecules move faster.","Wall collisions are more frequent and involve larger momentum changes.","Rate of momentum transfer and therefore pressure increase."]},
      activity:"Explain, using molecules, Boyle's law and Charles's law without using the ideal-gas equation.",
      mission:{goal:"Observe how invisible molecular collisions can drive visible Brownian motion.",steps:["Run at low temperature.","Increase temperature.","Compare the tracer's irregular motion."],record:"Describe tracer displacement over equal time intervals.",conclusion:"Explain why the tracer path is irregular rather than smooth."},
      check:["Brownian motion is evidence for…",["stationary molecules","continuous random molecular motion","gravity being absent","pressure being zero"],1,"Random bombardment by molecules drives the observed motion."],
      examTip:"For gas-law explanations, mention both collision rate and momentum change when relevant.",
      misconception:"Brownian particles are not individual gas molecules; they are larger visible particles being bombarded by molecules.",
      exit:"Explain why heating a fixed-volume gas increases pressure using momentum transfer."
    },
    {
      id:"kinetic-assumptions", code:"3.6.2.3", paper:"Paper 2", title:"Kinetic theory assumptions and pressure derivation", sim:"kineticTheory",
      lead:"Build the AQA kinetic-theory equation from momentum changes.",
      keywords:["kinetic theory","elastic collision","random motion","rms speed","momentum transfer"],
      formulas:["pV = (1/3)Nm⟨c²⟩","p = (1/3)ρ⟨c²⟩","crms = √⟨c²⟩"],
      objectives:["State the key ideal-gas assumptions used in kinetic theory.","Follow the algebraic momentum derivation.","Use the kinetic-theory pressure equation."],
      retrieval:[["Momentum of a molecule?","mc for velocity c."],["What is an elastic collision?","Total kinetic energy is conserved."],["What is pressure?","Force per unit area."]],
      teach:[
        ["Model assumptions","Treat molecules as point-like compared with their separation, moving randomly, interacting negligibly except during brief elastic collisions, and obeying Newtonian mechanics. Collisions with walls are elastic."],
        ["Single-wall collision","For a molecule with x-component c_x hitting a wall normally, momentum changes from +mc_x to −mc_x, so magnitude of momentum change is 2mc_x."],
        ["From one molecule to many","Collision frequency with the same wall is proportional to c_x/(2L). Combining momentum change and collision rate gives an average force contribution m c_x²/L. Summing over N molecules and using isotropy ⟨c_x²⟩ = ⟨c²⟩/3 leads to pV = (1/3)Nm⟨c²⟩."],
        ["Interpretation","The equation links a macroscopic quantity pV to microscopic mass and mean-square speed. The square root of ⟨c²⟩ is the rms speed."]
      ],
      worked:{q:"An ideal gas has density 1.2 kg m⁻³ and rms molecular speed 500 m s⁻¹. Estimate pressure.",steps:["p = (1/3)ρc_rms²","p = (1/3)×1.2×500² = 1.0×10⁵ Pa"]},
      activity:"Write the kinetic-theory derivation as a six-step chain: momentum change → collision time → force → sum → isotropy → pressure equation.",
      mission:{goal:"See the pressure equation emerge from collisions.",steps:["Fix N and volume.","Increase molecular speed.","Watch collision rate, impulse rate and pressure."],record:"Record crms and p for two states.",conclusion:"Check whether p scales approximately with crms²."},
      check:["The factor 1/3 appears because…",["one third of molecules exist","motion is randomly distributed among three spatial directions","volume is cubic","collisions lose one third of energy"],1,"For isotropic random motion, mean-square speed is shared equally among x, y and z components."],
      examTip:"In the derivation, use momentum change and collision rate carefully; do not skip the isotropy step that produces 1/3.",
      misconception:"The mean velocity of molecules can be zero while mean-square speed is non-zero.",
      exit:"Explain the physical origin of the 1/3 factor in the kinetic-theory equation."
    },
    {
      id:"molecular-ke", code:"3.6.2.3", paper:"Paper 2", title:"Temperature, molecular kinetic energy and ideal-gas internal energy", sim:"kineticTheory",
      lead:"Connect absolute temperature directly to microscopic kinetic energy.",
      keywords:["mean kinetic energy","Boltzmann constant","absolute temperature","monatomic ideal gas","internal energy"],
      formulas:["½m⟨c²⟩ = 3/2 kT","U = 3/2 NkT = 3/2 nRT (monatomic ideal gas)"],
      objectives:["Use the mean molecular kinetic-energy relation.","Explain temperature microscopically.","Relate ideal-gas internal energy to temperature."],
      retrieval:[["Kinetic-theory pressure equation?","pV = (1/3)Nm⟨c²⟩."],["Molecular ideal-gas equation?","pV = NkT."],["What is crms?","√⟨c²⟩."]],
      teach:[
        ["Combining equations","Set pV = NkT equal to pV = (1/3)Nm⟨c²⟩. Cancelling N gives kT = (1/3)m⟨c²⟩."],
        ["Mean kinetic energy","Multiplying by 3/2 gives ½m⟨c²⟩ = 3/2 kT. Thus absolute temperature is proportional to mean translational kinetic energy per molecule in the ideal-gas model."],
        ["Internal energy","For an ideal monatomic gas, intermolecular potential energy is neglected, so internal energy is the sum of molecular translational kinetic energies: U = (3/2)NkT = (3/2)nRT."],
        ["Historical understanding","Gas behaviour moved from empirical relationships to a successful molecular explanation as atomic theory and evidence such as Brownian motion developed."]
      ],
      worked:{q:"Find the mean translational kinetic energy of an ideal-gas molecule at 300 K.",steps:["Ēk = 3/2 kT","Ēk = 1.5×1.38×10⁻²³×300 = 6.21×10⁻²¹ J"]},
      activity:"Calculate how mean molecular KE changes when absolute temperature doubles, then predict the factor change in rms speed.",
      mission:{goal:"Connect T, mean KE and rms speed.",steps:["Choose one molecular mass.","Double T.","Compare mean KE and rms speed."],record:"Record T, Ēk and crms.",conclusion:"Explain why crms changes by √2 when T doubles."},
      check:["If absolute temperature doubles, mean molecular translational KE…",["halves","doubles","quadruples","is unchanged"],1,"Mean KE = 3/2 kT."],
      examTip:"Use absolute temperature and distinguish mean-square speed from mean speed.",
      misconception:"At a given temperature, different molecular masses have the same mean translational KE but different typical speeds.",
      exit:"Why do lighter molecules have a larger rms speed than heavier molecules at the same temperature?"
    }
  ],

  spec: [
    ["3.6.1.1","Circular motion","Radian measure; angular speed; v = ωr; centripetal acceleration; centripetal force.","radians"],
    ["3.6.1.2","Simple harmonic motion","SHM condition; defining equation; x, v and a graphs; phase; maximum speed and acceleration.","shm-condition"],
    ["3.6.1.3","Simple harmonic systems","Mass–spring; pendulum; energy with displacement/time; damping.","spring"],
    ["RP7","Required Practical 7","Mass–spring and simple-pendulum investigation of SHM.","spring"],
    ["3.6.1.4","Forced vibrations and resonance","Free/forced vibrations; resonance; damping and resonance sharpness; mechanical and stationary-wave examples.","resonance"],
    ["3.6.2.1","Thermal energy transfer","Internal energy; heating/work; state changes; Q=mcΔT; continuous flow; Q=ml; experimental errors.","internal-energy"],
    ["3.6.2.2","Ideal gases","Gas laws; absolute zero; pV=nRT; pV=NkT; N_A, R, k; molar and molecular mass.","gas-laws"],
    ["RP8","Required Practical 8","Boyle's law at constant temperature and Charles's law at constant pressure.","rp8-boyle"],
    ["3.6.2.3","Molecular kinetic theory","Brownian motion; molecular explanations of gas laws; model assumptions; pressure derivation; mean molecular KE; ideal-gas internal energy.","brownian-model"]
  ],

  quiz: [
    ["3.6.1.1","One complete revolution equals…",["π rad","2π rad","360 rad","1 rad"],1,"Use the radian definition.","A full revolution is 2π rad."],
    ["3.6.1.1","At fixed radius, doubling tangential speed makes centripetal acceleration…",["double","four times","half","unchanged"],1,"a = v²/r.","The square gives a factor of four."],
    ["3.6.1.1","Centripetal force is best described as…",["an extra force","the inward resultant of real forces","always tension","always friction"],1,"Think resultant force.","It is the inward resultant."],
    ["3.6.1.2","The defining SHM equation is…",["a=+ω²x","a=−ω²x","v=−ω²x","F=constant"],1,"Acceleration is restoring.","a = −ω²x."],
    ["3.6.1.2","At equilibrium in ideal SHM…",["speed is maximum","speed is zero","acceleration is maximum","PE is maximum"],0,"Think energy transfer.","Speed is maximum."],
    ["3.6.1.2","Acceleration is out of phase with displacement by…",["π/4","π/2","π","2π"],2,"They have opposite signs.","π rad."],
    ["3.6.1.3","For a mass–spring system, T is proportional to…",["m","√m","1/m","m²"],1,"T = 2π√(m/k).","T ∝ √m."],
    ["3.6.1.3","The simple-pendulum period formula relies on…",["large angles","small-angle approximation","bob mass","air resistance"],1,"sinθ ≈ θ.","Small angles in radians."],
    ["3.6.1.3","At a turning point in ideal spring SHM…",["KE maximum","PE maximum","total energy zero","acceleration zero"],1,"v = 0 there.","PE is maximum."],
    ["3.6.1.4","Resonance occurs when…",["drive frequency ≈ natural frequency","amplitude is zero","damping is infinite","frequency is zero"],0,"Compare two frequencies.","Driving and natural frequencies match closely."],
    ["3.6.2.1","Internal energy is the sum of random particle…",["KE only","PE only","KE and PE","chemical energy only"],2,"Use the definition.","Random KE + PE."],
    ["3.6.2.1","During a phase change at constant temperature, supplied energy mainly changes…",["mean KE","particle PE","mass","specific heat capacity"],1,"Temperature is unchanged.","Particle potential-energy contribution changes."],
    ["3.6.2.1","The equation for a temperature change is…",["Q=ml","Q=mcΔT","pV=nRT","P=IV only"],1,"Specific heat capacity.","Q = mcΔT."],
    ["3.6.2.1","At fixed heater power, doubling mass flow rate ideally makes ΔT…",["double","half","unchanged","four times"],1,"P = ṁcΔT.","It halves."],
    ["3.6.2.1","Specific latent heat has unit…",["J kg⁻¹","J kg⁻¹ K⁻¹","W kg⁻¹","Pa"],0,"Energy per mass.","J kg⁻¹."],
    ["3.6.2.2","Boyle's law requires constant…",["pressure","temperature","volume","particle speed"],1,"pV constant.","Temperature."],
    ["3.6.2.2","Charles's law uses temperature measured in…",["°C","K","either without conversion","J"],1,"Absolute temperature.","Kelvin."],
    ["3.6.2.2","The molar ideal-gas equation is…",["pV=NkT","pV=nRT","pV=1/3Nm<c²>","Q=mcΔT"],1,"Use n moles.","pV = nRT."],
    ["3.6.2.2","The molecular ideal-gas equation is…",["pV=NkT","pV=nRT only","p/T=constant only","F=ma"],0,"Use N molecules.","pV = NkT."],
    ["3.6.2.2","R is related to k by…",["R=k/N_A","R=N_Ak","R=N_A/k","R=k"],1,"Move between per mole and per particle.","R=N_Ak."],
    ["3.6.2.3","Brownian motion provides evidence for…",["stationary atoms","random molecular motion","zero pressure","absolute rest"],1,"Think bombardment.","Random molecular motion."],
    ["3.6.2.3","Gas pressure is caused microscopically by…",["weight only","momentum transfer in wall collisions","molecules sticking permanently","potential energy only"],1,"Newton's laws.","Momentum transfer."],
    ["3.6.2.3","Kinetic theory gives…",["pV=1/3Nm<c²>","pV=Nm<c>","pV=3Nm<c²>","p=mc"],0,"Recall the 1/3 factor.","pV = (1/3)Nm<c²>."],
    ["3.6.2.3","Mean molecular translational KE is…",["kT","1/2kT","3/2kT","3kT"],2,"Three translational directions.","3/2 kT."],
    ["3.6.2.3","At the same T, lighter and heavier ideal-gas molecules have the same…",["rms speed","mean translational KE","momentum magnitude","mass"],1,"KE depends only on T in this model.","Mean translational KE is the same."]
  ]
};