(function(){
'use strict';
var DATA=window.FM_DATA||{lessons:[]},$=function(s,r){return(r||document).querySelector(s)},$$=function(s,r){return Array.from((r||document).querySelectorAll(s))};
var KEY='fm-mastery-v5',RKEY='fm-retrieval-v5';
function load(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch(e){return f}}
var state=Object.assign({xp:0,attempts:0,correct:0,skills:{calculations:0,graphs:0,uncertainty:0,derivations:0,explanations:0,practicals:0,synoptic:0},topics:{},recent:[],exam:{earned:0,total:0},challenge:0},load(KEY,{}));
state.skills=Object.assign({calculations:0,graphs:0,uncertainty:0,derivations:0,explanations:0,practicals:0,synoptic:0},state.skills||{});state.topics=state.topics||{};state.recent=state.recent||[];state.exam=state.exam||{earned:0,total:0};
var reviews=load(RKEY,[]);
function save(){localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(RKEY,JSON.stringify(reviews))}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function topicName(id){var l=DATA.lessons.find(function(x){return x.id===id});return l?l.title:id}
function pretty(k){return({calculations:'Calculations',graphs:'Graphs',uncertainty:'Uncertainty',derivations:'Derivations',explanations:'Explanations',practicals:'Practical skills',synoptic:'Synoptic'}[k]||k)}
function result(skill,topic,ok,label,xp){state.attempts++;if(ok)state.correct++;state.skills[skill]=clamp((state.skills[skill]||0)+(ok?5:-1),0,100);state.topics[topic]=clamp((state.topics[topic]||0)+(ok?6:-2),0,100);state.xp+=(xp==null?(ok?10:2):xp);state.recent.unshift({time:Date.now(),skill:skill,topic:topic,correct:ok,label:label||''});state.recent=state.recent.slice(0,40);save();if($('#masteryXP'))$('#masteryXP').textContent=state.xp}
function schedule(topic,prompt,answer){if(!reviews.some(function(r){return r.topic===topic&&r.prompt===prompt&&r.stage<5})){reviews.push({id:String(Date.now())+Math.random(),topic:topic,prompt:prompt,answer:answer,stage:0,due:Date.now()+86400000});save()}}
function gradeReview(id,ok){var r=reviews.find(function(x){return x.id===id});if(!r)return;if(ok){r.stage++;var gaps=[1,3,7,21,60];r.due=Date.now()+gaps[Math.min(r.stage,gaps.length-1)]*86400000;if(r.stage>=5)reviews=reviews.filter(function(x){return x.id!==id})}else{r.stage=0;r.due=Date.now()+86400000}save();renderRetrieval();renderDashboard()}
function mastery(){var complete=load('fm36-completed',[]).length/Math.max(1,DATA.lessons.length),perf=state.attempts?state.correct/state.attempts:0,skill=Object.values(state.skills).reduce(function(a,b){return a+b},0)/700;return Math.round((complete*.45+perf*.35+skill*.20)*100)}
var modes=[
 ['dashboard','Dashboard'],['adaptive','Adaptive path'],['calculations','Calculation mastery'],['examiner','Examiner mode'],['graphs','Graphs & uncertainty'],['derivations','Derivation builder'],['diagnostics','Misconceptions'],['command','Command words'],['practicalplan','Practical planner'],['datalab','Data analysis'],['synoptic','Synoptic & A*'],['retrieval','Spaced retrieval'],['equationmap','Equation map'],['teacher','Teacher mode'],['presentation','Presentation'],['access','EAL & accessibility']
];
function init(){var h=$('#masteryHost');if(!h)return;h.innerHTML='<div class="mastery-toolbar panel"><div><span class="eyebrow">Personalised learning</span><h2>Mastery Hub</h2></div><label class="mastery-select"><span>Tool</span><select id="masteryMode">'+modes.map(function(m){return'<option value="'+m[0]+'">'+m[1]+'</option>'}).join('')+'</select></label><div class="mastery-xp"><strong id="masteryXP">'+state.xp+'</strong><span>XP</span></div></div><div class="mastery-shortcuts">'+modes.slice(0,6).map(function(m){return'<button class="mastery-shortcut" data-mastery-jump="'+m[0]+'"><strong>'+m[1]+'</strong></button>'}).join('')+'</div><div id="masteryPanel"></div>';$('#masteryMode').addEventListener('change',function(){renderMode(this.value)});$$('[data-mastery-jump]').forEach(function(b){b.addEventListener('click',function(){$('#masteryMode').value=b.dataset.masteryJump;renderMode(b.dataset.masteryJump)})});renderMode('dashboard')}
function renderMode(m){var fn=window.FM_MASTERY_MODES&&window.FM_MASTERY_MODES[m];if(fn)return fn();({dashboard:renderDashboard,adaptive:renderAdaptive,retrieval:renderRetrieval,equationmap:renderEquationMap}[m]||renderDashboard)()}
function renderDashboard(){if($('#masteryMode')&&$('#masteryMode').value!=='dashboard')return;var h=$('#masteryPanel');if(!h)return;var skills=Object.entries(state.skills),weak=skills.slice().sort(function(a,b){return a[1]-b[1]}).slice(0,3),completed=load('fm36-completed',[]).length;h.innerHTML='<div class="mastery-grid"><article class="panel pad mastery-score"><span class="eyebrow">Overall mastery</span><div class="ring"><strong>'+mastery()+'%</strong></div><p>'+completed+'/'+DATA.lessons.length+' lessons complete · '+state.correct+'/'+state.attempts+' practice attempts correct</p></article><article class="panel pad"><h3>Recommended focus</h3>'+weak.map(function(w){return'<div class="focus-row"><span>'+pretty(w[0])+'</span><div class="mini-track"><i style="width:'+w[1]+'%"></i></div><strong>'+w[1]+'%</strong></div>'}).join('')+'<button class="button primary" data-open-adaptive>Build my next session</button></article></div><div class="panel pad"><h3>Skill heat map</h3><div class="heat-grid">'+skills.map(function(s){return'<div class="heat-cell level-'+Math.min(4,Math.floor(s[1]/25))+'"><strong>'+pretty(s[0])+'</strong><span>'+s[1]+'%</span></div>'}).join('')+'</div></div><div class="mastery-grid"><article class="panel pad"><h3>Spaced retrieval</h3><p><strong>'+reviews.filter(function(r){return r.due<=Date.now()}).length+'</strong> due now.</p><button class="button" data-mode="retrieval">Review</button></article><article class="panel pad"><h3>Exam record</h3><p><strong>'+state.exam.earned+'/'+state.exam.total+'</strong> self-marked points.</p><button class="button" data-mode="examiner">Examiner mode</button></article><article class="panel pad"><h3>A* challenge</h3><p><strong>'+state.challenge+'</strong> challenges completed.</p><button class="button" data-mode="synoptic">Challenge pathway</button></article></div>';if($('[data-open-adaptive]'))$('[data-open-adaptive]').onclick=function(){$('#masteryMode').value='adaptive';renderAdaptive()};$$('[data-mode]').forEach(function(b){b.onclick=function(){$('#masteryMode').value=b.dataset.mode;renderMode(b.dataset.mode)}})}
function recommendations(){var a=[],sw=Object.entries(state.skills).sort(function(x,y){return x[1]-y[1]})[0],tw=Object.entries(state.topics).sort(function(x,y){return x[1]-y[1]})[0],due=reviews.filter(function(r){return r.due<=Date.now()}).length;if(sw)a.push({title:'Build '+pretty(sw[0]),why:'Current mastery '+sw[1]+'%',mode:sw[0]==='calculations'?'calculations':(sw[0]==='graphs'||sw[0]==='uncertainty'?'graphs':sw[0]==='derivations'?'derivations':sw[0]==='practicals'?'practicalplan':'examiner')});if(tw)a.push({title:'Revisit '+topicName(tw[0]),why:'Weak topic signal '+tw[1]+'%',lesson:tw[0]});if(due)a.push({title:'Complete '+due+' spaced reviews',why:'Due now',mode:'retrieval'});if(a.length<3)a.push({title:'Try a synoptic challenge',why:'Build unfamiliar-problem skill',mode:'synoptic'});return a.slice(0,4)}
function renderAdaptive(){var h=$('#masteryPanel'),r=recommendations();h.innerHTML='<div class="panel pad"><span class="eyebrow">Adaptive learning path</span><h3>Your next best session</h3><p class="muted">This route updates from lesson completion and Mastery Hub attempts stored on this device.</p><div class="adaptive-route">'+r.map(function(x,i){return'<article class="route-step"><span>'+(i+1)+'</span><div><strong>'+x.title+'</strong><small>'+x.why+'</small></div><button class="button" data-route="'+i+'">Open</button></article>'}).join('')+'</div></div>';$$('[data-route]').forEach(function(b){b.onclick=function(){var x=r[+b.dataset.route];if(x.lesson&&window.FM_APP)window.FM_APP.openLessonById(x.lesson);else if(x.mode){$('#masteryMode').value=x.mode;renderMode(x.mode)}}})}
function renderRetrieval(){var h=$('#masteryPanel');if(!h)return;var due=reviews.filter(function(r){return r.due<=Date.now()}).slice(0,12);h.innerHTML='<div class="panel pad"><span class="eyebrow">Spaced retrieval</span><h3>'+due.length+' due now</h3>'+(due.length?due.map(function(r){return'<article class="review-card"><span class="data-badge">'+topicName(r.topic)+'</span><p><strong>'+r.prompt+'</strong></p><button class="text-button" data-show-review="'+r.id+'">Reveal</button><div class="review-answer hidden" id="r-'+r.id.replace(/\./g,'')+'"><p>'+r.answer+'</p><div class="button-row"><button class="button" data-grade-review="'+r.id+'|0">Again</button><button class="button primary" data-grade-review="'+r.id+'|1">Got it</button></div></div></article>'}).join(''):'<div class="empty-state"><strong>Nothing due right now.</strong><p>Practice elsewhere in the hub automatically creates future review items.</p></div>')+'</div>';$$('[data-show-review]').forEach(function(b){b.onclick=function(){var id='r-'+b.dataset.showReview.replace(/\./g,'');$('#'+id).classList.toggle('hidden')}});$$('[data-grade-review]').forEach(function(b){b.onclick=function(){var p=b.dataset.gradeReview.split('|');gradeReview(p[0],p[1]==='1')}})}
function renderEquationMap(){var h=$('#masteryPanel'),groups=[['Circular motion',['ω=2πf','v=ωr','a=v²/r','F=mv²/r']],['SHM',['a=−ω²x','vmax=ωA','T=2π√(m/k)','T=2π√(L/g)','E=½kA²']],['Thermal',['Q=mcΔT','P=ṁcΔT','Q=ml','E=Pt']],['Ideal gas',['pV=nRT','N=nNₐ','R=Nₐk','pV=NkT']],['Kinetic theory',['pV=(1/3)Nm<c²>','½m<c²>=3/2kT','cᵣₘₛ=√(3kT/m)','U=3/2nRT']]];h.innerHTML='<div class="panel pad"><span class="eyebrow">Equation connections</span><h3>Equation map</h3><div class="equation-map">'+groups.map(function(g){return'<section><h4>'+g[0]+'</h4><div class="map-chain">'+g[1].map(function(n,i){return'<button class="map-node">'+n+'</button>'+(i<g[1].length-1?'<span>→</span>':'')}).join('')+'</div></section>'}).join('')+'</div><p class="muted">Use Calculation Mastery to practise the numbers and Derivation Builder to reconstruct the links between equations.</p></div>'}
window.FM_MASTERY={state:state,reviews:function(){return reviews},result:result,schedule:schedule,save:save,renderDashboard:renderDashboard,renderMode:renderMode,topicName:topicName,pretty:pretty,mastery:mastery};
window.FM_MASTERY_MODES=window.FM_MASTERY_MODES||{};
document.addEventListener('DOMContentLoaded',init);
})();